name: 🐛 Bug Report
description: Found a bug? Help us squash it.
labels: ["bug"]

body:

- type: markdown
  attributes:
    value: |
      Please be aware that Helium is free and is not under active development. Though [supporting the project financially](https://github.com/sponsors/alexdlaird) is appreciated ❤️ (since Helium has operating costs, even though it is free to use), we make no guarantees bug reports will be looked at or considered.

      Though this project is not under active development, we are still happy to review pull requests submitted by the community to resolve bugs, so submitting a report of your experience may still be helpful to us and others.

- type: checkboxes
  id: ack
  attributes:
    label: Acknowledgements
    options:
    - label: I have written a descriptive issue title
      required: true
    - label: I have searched [Issues](issues?q=is%3Aissue) to see if the bug has already been reported
      required: true

- type: input
  id: os-version
  attributes:
    label: Operating System
    placeholder: macOS 10.14.5
  validations:
    required: true

- type: input
  id: browser-version
  attributes:
    label: Browser & Version
    placeholder: Chrome 122.0.6261.57
  validations:
    required: true

- type: input
  id: username
  attributes:
    label: Helium Username
    placeholder: contact@alexlaird.com
  validations:
    required: true

- type: textarea
  id: describe-the-bug
  attributes:
    label: Describe the Bug
    description: |
      A clear and concise description of what the bug is and the steps you took that caused it.

      Please note that we need details to troubleshoot. "Creating an assignment didn't work" is not a helpful description of an error and will likely just be closed. What was the name of the assignment? Course Group? Did it have Categories? Whatever the issue, we need contextual details surrounding it to be able to troubleshoot the issue.
  validations:
    required: true

- type: textarea
  id: expected-behavior
  attributes:
    label: Expected Behavior
    description: A brief description of what you expected to happen.
    
- type: textarea
  id: console-output
  attributes:
    label: Console Output / Error Responses
    description: If you're a superuser, please provide any stacktraces or responses from failed requests in the browser's debugger console.
